// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC60TdH0Z1lpPM7LvvmaPaTwD5xoIFqIiQ',
    appId: '1:1069917074856:web:ad33de48ffe98933ffd99d',
    messagingSenderId: '1069917074856',
    projectId: 'blockerino-v2',
    authDomain: 'blockerino-v2.firebaseapp.com',
    storageBucket: 'blockerino-v2.firebasestorage.app',
    measurementId: 'G-HET0SNGYF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7ngIvkcMso9UQsYDGLVfXX6tDzkzMoc',
    appId: '1:1069917074856:android:a82e2820235ac59cffd99d',
    messagingSenderId: '1069917074856',
    projectId: 'blockerino-v2',
    storageBucket: 'blockerino-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASP1u4ShRl6Ze3sfmKmIR37wnATE_7iE4',
    appId: '1:1069917074856:ios:ff472c128e8ee784ffd99d',
    messagingSenderId: '1069917074856',
    projectId: 'blockerino-v2',
    storageBucket: 'blockerino-v2.firebasestorage.app',
    iosBundleId: 'com.example.blockerinoV2',
  );
}
